version: '3.8'
services:
    mysql.wuxt:
        container_name: ${WUXT_MYSQL_CONTAINER:-mysql.wuxt}
        image: mysql:8
        volumes:
            - ./_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: dev
        networks:
          - default

    wp.wuxt:
        container_name: ${WUXT_WP_CONTAINER:-wp.wuxt}
        image: wordpress:5.5.1-php7.4-apache
        volumes:
          - ./wp-content:/var/www/html/wp-content:rw,cached          
        expose:
          - '${WUXT_PORT_BACKEND:-3080}'
        ports:
          - '${WUXT_PORT_BACKEND:-3080}:80'
        environment:
          WORDPRESS_DB_HOST: ${WUXT_MYSQL_CONTAINER:-mysql.wuxt}:3306
          WORDPRESS_DB_NAME: wuxt
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: dev
          WUXT_PORT_BACKEND: ${WUXT_PORT_BACKEND:-3080}
          WORDPRESS_CONFIG_EXTRA: |
            define('WP_SITEURL', 'http://localhost:${WUXT_PORT_BACKEND:-3080}' );
            define('WP_HOME', 'http://localhost:${WUXT_PORT_BACKEND:-3080}' );        
            define('FS_METHOD', 'direct');
        networks:
          - default

    front.wuxt:
        container_name: ${WUXT_NUXT_CONTAINER:-front.wuxt}
        image: node:12
        working_dir: '/var/www/app'
        environment:
            - HOST=0.0.0.0
            - WUXT_WP_CONTAINER=${WUXT_WP_CONTAINER:-wp.wuxt}
            - WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3080}
        ports:
            - '${WUXT_PORT_FRONTEND-3000}:3000'
            - "8000:8000"
        volumes:
            - ./nuxt:/var/www/app
            - ./_scripts/front-init-vueui.sh:/var/www/app/init.sh
        #command: bash -c "yarn global add @vue/cli && yarn install && WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3080} yarn dev"
        entrypoint: /var/www/app/init.sh
        networks:
          - default

networks:
    default:
